### PR TITLE
modified return from post

### PR DESCRIPTION
**Pull request by ayeolakenny**

### CODE REVIEW

**Comment by ayeolakenny** [comment]
Hi @Ananto30 i fixed it, kindly review thanks :)

**Comment by Ananto30** [comment]
Thanks for contribution 👏

**Comment by ayeolakenny** [comment]
any other stuff i can help with? @Ananto30

**Comment by Ananto30** [comment]
@ayeolakenny Please check the https://github.com/Ananto30/golpo-express/issues?q=is%3Aissue+is%3Aopen+label%3AHacktoberfest pick any you like. Thanks 🙏

**Pull request merged**
