### PR TITLE
Update text to url and added validation

### PR DESCRIPTION
**Pull request by alammoiz**

### CODE REVIEW

**Comment by Ananto30** [comment]
It's not working 😟 Am I missing something?

image

**Comment by alammoiz** [comment]
I have updated the schema, please try with url not text @Ananto30

**Comment by Ananto30** [comment]
Still not working 😟
I think we can check this inside the controller method `createPost`. And please test before pushing 🙏

You need to add `not()` and this works
```
body("url", "Adult contents are not allowed").not().isIn(adultURLs)
```
**But only for the exact match, like if I put exactly "https://www.timeout.com"**

So this is not the solution I think. If the express-validator cannot do this, we can always write a method to do that 😃

**Comment by alammoiz** [comment]
> Still not working 😟 I think we can check this inside the controller method `createPost`. And please test before pushing 🙏
> 
> You need to add `not()` and this works
> 
> ```
> body("url", "Adult contents are not allowed").not().isIn(adultURLs)
> ```
> 
> **But only for the exact match, like if I put exactly "https://www.timeout.com"**
> 
> So this is not the solution I think. If the express-validator cannot do this, we can always write a method to do that 😃

You're Right. But I'm not an expert in express-validator. So, I have pushed the code with only this fix that you have mentioned. Can you please merge this PR or open another ticket for custom validation. I shall be very thankful if you could do this. 😃

**Comment by Ananto30** [comment]
Thanks @alammoiz 
Rest of the task transferred to https://github.com/Ananto30/golpo-express/issues/14

**Pull request merged**
